.TH sarmake 1 "January 7, 2010" "version 20100107" "USER COMMANDS"
.SH NAME
.HP
.B sarmake
\- for creating (O)NScripter SAR archive files
.SH SYNOPSIS
.HP
.B "sarmake" 
.IB arc_file " -d " in_dir
.P
.B sarmake
.I arc_file in_file "..."

.SH DESCRIPTION
This tool produces SAR archives for use with NScripter, ONScripter or
PONScripter titles either from a list of files given on the command line or
from a directory of files.
.SH OPTIONS
.TP
.BI "-d " in_dir
Builds an archive from the directory
.IR in_dir ".  "
The top-level directory
.I in_dir
will not be included in pathnames stored in the archive.
.TP
.I in_file "..."
A list of files and/or directories to be included in the archive.

.SH EXAMPLES
.TP
Create an archive called "arc.sar" from a directory called "arc":
.B sarmake
arc.sar
.BR -d " arc"
.TP
Create an archive called "arc.sar" with the directories "img" and "bgm" and their contents:
.B sarmake
arc.sar img bgm
.SH EXIT STATUS
.B sarmake
returns zero on success and a nonzero value if an error occurs.
.SH AUTHOR
Ogapee <ogapee@aqua.dti2.ne.jp>, "Uncle" Mion Sonozaki <UncleMion@gmail.com>

http://onscripter.denpa.mobi/
.SH SEE ALSO
.BR sardec "(1), " sarconv "(1), " nsamake "(1), " ns2make (1)

