#!/bin/sh
if test "$1" = "--ftversion"; then
    echo "2.13.0"
elif test "$1" = "--cflags"; then
    echo "-I$(pwd)/extlib/include/freetype2 -I$(pwd)/extlib/include"
elif test "$1" = "--libs"; then
    echo "-L$(pwd)/extlib/lib -lfreetype -lz"
else
    echo "This is a hacky fix for the new freetype version seemingly not generating freetype-config. Hopefully it doesn't break too easily."
    echo "Accepted options:"
    echo -e "\t--ftversion"
    echo -e "\t--cflags"
    echo -e "\t--libs"
    echo
    echo "-Galladite 2023-5-16"
fi
